# Generated by Django 5.2.5 on 2025-08-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='name',
            new_name='username',
        ),
    ]
