# Generated by Django 5.2.5 on 2025-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_studentregistration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
