# Generated by Django 5.2.5 on 2025-08-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentregistration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='name',
        ),
    ]
